"use client";

import { ArrowLeft, ShieldCheck } from "lucide-react";
import Link from "next/link";
import { useEffect, useRef, useState } from "react";
import BrandMark from "../brand-mark";

type Locale = "en" | "fr" | "es";
const policy = {
  en: { language: "Language", back: "Back to Blossom Royall", eyebrow: "PRIVACY POLICY", title: "Your information belongs to you.", updated: "Last updated August 28, 2026", intro: "This policy explains how Blossom Royall and its independent stores use information when you browse, create an account, shop, work, or operate a store.", collect: "Information we collect", collectItems: ["Account and contact information, including name, email, phone, and role.", "Optional fit measurements, preferences, addresses, and customer service content.", "Orders, products, inventory, payments, receipts, returns, vendor, lease, and workforce records needed to operate the mall.", "Payment references and optional proof files. Card credentials are not stored by Blossom Royall.", "Security, audit, device, and diagnostic information needed to protect accounts and maintain the service."], use: "How we use information", useItems: ["Provide account, shopping, fulfillment, vendor, staff, receipt, and support functions.", "Protect tenant boundaries, prevent fraud, reconcile payments, and maintain accountable records.", "Personalize fit and shopping only when the customer provides the information and applicable consent."], share: "How information is shared", shareItems: ["Relevant order and fulfillment details are shared with the independent vendor responsible for an item.", "Service providers such as Supabase and approved payment, delivery, messaging, or monitoring providers receive only information needed for their contracted function.", "We do not sell personal information or use it for cross company advertising tracking."], retention: "Retention and deletion", retentionText: "Personal information is retained only while needed for the service, security, disputes, or legal obligations. Account deletion can be initiated in the app or on the account deletion web page. Personal content is deleted during completion. Required transaction records may be retained in anonymized form for tax, fraud, dispute, or legal obligations.", choices: "Your choices", choicesText: "You may access or correct account information, export or delete My Fit, control vendor sharing, withdraw optional consent, and request full account deletion. A sole store owner must first transfer ownership so the tenant is not abandoned.", security: "Security", securityText: "Blossom Royall uses tenant row level security, role scoped access, owner multifactor authentication, private evidence storage, audit records, encrypted transport, and release security checks. No system can guarantee absolute security.", contact: "Privacy contact", contactText: "For privacy questions, use in app Help or email privacy@blossomroyall.com. This address must be activated before public app store submission.", delete: "Manage or delete my account" },
  fr: { language: "Langue", back: "Retour à Blossom Royall", eyebrow: "POLITIQUE DE CONFIDENTIALITÉ", title: "Vos informations vous appartiennent.", updated: "Mise à jour le 28 août 2026", intro: "Cette politique explique comment Blossom Royall et ses magasins indépendants utilisent les informations lorsque vous naviguez, créez un compte, achetez, travaillez ou exploitez un magasin.", collect: "Informations collectées", collectItems: ["Informations de compte et de contact, notamment nom, courriel, téléphone et rôle.", "Mesures facultatives, préférences, adresses et contenu du service client.", "Commandes, produits, stocks, paiements, reçus, retours, vendeurs, baux et dossiers du personnel nécessaires au centre commercial.", "Références de paiement et preuves facultatives. Blossom Royall ne conserve pas les données de carte.", "Informations de sécurité, d’audit, d’appareil et de diagnostic nécessaires au service."], use: "Utilisation des informations", useItems: ["Fournir les fonctions de compte, achat, livraison, vendeur, personnel, reçu et assistance.", "Protéger les locataires, prévenir la fraude, rapprocher les paiements et tenir des dossiers responsables.", "Personnaliser la taille et les achats uniquement avec les informations et le consentement du client."], share: "Partage des informations", shareItems: ["Les détails utiles de commande sont partagés avec le vendeur indépendant responsable.", "Les prestataires approuvés reçoivent uniquement les informations nécessaires à leur fonction.", "Nous ne vendons pas les informations personnelles et ne faisons pas de suivi publicitaire interentreprises."], retention: "Conservation et suppression", retentionText: "Les informations sont conservées uniquement pour le service, la sécurité, les litiges ou les obligations légales. La suppression peut être demandée dans l’application ou sur la page web dédiée. Les transactions exigées peuvent être conservées anonymement.", choices: "Vos choix", choicesText: "Vous pouvez corriger vos informations, exporter ou supprimer My Fit, contrôler le partage vendeur, retirer un consentement facultatif et demander la suppression complète. Le propriétaire unique doit d’abord transférer la propriété.", security: "Sécurité", securityText: "Blossom Royall utilise la sécurité par locataire, les rôles, l’authentification multifacteur propriétaire, le stockage privé, les audits, le transport chiffré et des contrôles de sortie.", contact: "Contact confidentialité", contactText: "Utilisez l’aide intégrée ou écrivez à privacy@blossomroyall.com. Cette adresse doit être activée avant la soumission publique.", delete: "Gérer ou supprimer mon compte" },
  es: { language: "Idioma", back: "Volver a Blossom Royall", eyebrow: "POLÍTICA DE PRIVACIDAD", title: "Su información le pertenece.", updated: "Actualizada el 28 de agosto de 2026", intro: "Esta política explica cómo Blossom Royall y sus tiendas independientes usan información cuando navega, crea una cuenta, compra, trabaja u opera una tienda.", collect: "Información recopilada", collectItems: ["Información de cuenta y contacto, incluido nombre, correo, teléfono y función.", "Medidas opcionales, preferencias, direcciones y contenido de atención al cliente.", "Pedidos, productos, inventario, pagos, recibos, devoluciones, vendedores, contratos y registros laborales necesarios para operar el centro comercial.", "Referencias de pago y pruebas opcionales. Blossom Royall no almacena credenciales de tarjetas.", "Información de seguridad, auditoría, dispositivo y diagnóstico necesaria para mantener el servicio."], use: "Cómo usamos la información", useItems: ["Proporcionar funciones de cuenta, compra, entrega, vendedor, personal, recibos y asistencia.", "Proteger los límites de cada tienda, prevenir fraude, conciliar pagos y mantener registros responsables.", "Personalizar talla y compras únicamente con la información y el consentimiento correspondiente."], share: "Cómo se comparte", shareItems: ["Los datos relevantes del pedido se comparten con el vendedor independiente responsable.", "Los proveedores aprobados reciben solo la información necesaria para su función contratada.", "No vendemos información personal ni la usamos para seguimiento publicitario entre empresas."], retention: "Retención y eliminación", retentionText: "La información se conserva solo para el servicio, seguridad, disputas u obligaciones legales. La eliminación puede iniciarse en la aplicación o en la página web. Los registros obligatorios pueden conservarse de forma anónima.", choices: "Sus opciones", choicesText: "Puede corregir información, exportar o eliminar My Fit, controlar el intercambio con vendedores, retirar consentimiento opcional y solicitar la eliminación completa. El único propietario debe transferir primero la propiedad.", security: "Seguridad", securityText: "Blossom Royall usa seguridad por tienda, funciones limitadas, autenticación multifactor del propietario, almacenamiento privado, auditorías, transporte cifrado y controles de lanzamiento.", contact: "Contacto de privacidad", contactText: "Use la ayuda integrada o escriba a privacy@blossomroyall.com. Esta dirección debe activarse antes de la presentación pública.", delete: "Administrar o eliminar mi cuenta" },
} as const;

export default function PrivacyPage() {
  const [locale, setLocale] = useState<Locale>("en");
  const languageSelected = useRef(false);
  useEffect(() => {
    const stored = localStorage.getItem("br-public-language") as Locale | null;
    const candidate = stored && stored in policy ? stored : navigator.language.slice(0, 2) as Locale;
    if (!languageSelected.current && candidate in policy) setLocale(candidate);
  }, []);
  const t = policy[locale];
  return <main className="privacy-page"><article>
    <header><Link href="/welcome"><ArrowLeft />{t.back}</Link><label>{t.language}<select value={locale} onChange={(event) => { const next = event.target.value as Locale; languageSelected.current = true; localStorage.setItem("br-public-language", next); setLocale(next); }}><option value="en">English</option><option value="fr">Français</option><option value="es">Español</option></select></label></header>
    <BrandMark /><span className="eyebrow">{t.eyebrow}</span><h1>{t.title}</h1><time>{t.updated}</time><p className="privacy-intro">{t.intro}</p>
    <section><h2>{t.collect}</h2><ul>{t.collectItems.map((item) => <li key={item}>{item}</li>)}</ul></section>
    <section><h2>{t.use}</h2><ul>{t.useItems.map((item) => <li key={item}>{item}</li>)}</ul></section>
    <section><h2>{t.share}</h2><ul>{t.shareItems.map((item) => <li key={item}>{item}</li>)}</ul></section>
    <section><h2>{t.retention}</h2><p>{t.retentionText}</p></section><section><h2>{t.choices}</h2><p>{t.choicesText}</p></section><section><h2>{t.security}</h2><p>{t.securityText}</p></section><section><h2>{t.contact}</h2><p>{t.contactText}</p></section>
    <Link className="primary privacy-delete" href="/account/delete"><ShieldCheck />{t.delete}</Link>
    <footer><b>Powered by TA Tech</b><span>Is not where you have been but where you are going.</span></footer>
  </article></main>;
}
